### ISSUE TITLE
[1.18.2] Cannot invoke "net.minecraft.world.level.biome.Biome.getRegistryName()" because "biome" is null

### ISSUE THREAD

**Issue by OcrSu** [evanpickett/Annolike-Fertility#1]
[crash-2022-10-11_19.22.38-server.txt](https://github.com/evanpickett/Annolike-Fertility/files/9754617/crash-2022-10-11_19.22.38-server.txt)

**Comment by evanpickett** [comment]
fixed in 1.21, being uploaded to curseforge!

**Comment by OcrSu** [comment]
[crash-2022-10-16_07.40.42-client.txt](https://github.com/evanpickett/Annolike-Fertility/files/9793306/crash-2022-10-16_07.40.42-client.txt)
The game crashes after I connect to the forge server

**Comment by OcrSu** [comment]
@evanpickett

**Comment by evanpickett** [comment]
will fix!

**Comment by evanpickett** [comment]
fixed in 1.22, uploading to curseforge. There may be some other places this can occur so if there are any other crashes, keep posting your logs. Makes it super easy to fix!
