### ISSUE TITLE
[1.18.2]Sever Crash When Player Connect the Server

### ISSUE THREAD

**Issue by OcrSu** [evanpickett/Annolike-Fertility#2]
[crash-2022-10-25_19.08.00-server.txt](https://github.com/evanpickett/Annolike-Fertility/files/9859675/crash-2022-10-25_19.08.00-server.txt)
[debug.log](https://github.com/evanpickett/Annolike-Fertility/files/9859677/debug.log)

When I connect to my server, the server crashes
The client shows: Server closed .
The client did not crash

**Comment by evanpickett** [comment]
Should be fixed in v. 1.23
